// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SmartCampaignSuggestServiceClient is the client API for SmartCampaignSuggestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartCampaignSuggestServiceClient interface {
	// Returns BudgetOption suggestions.
	SuggestSmartCampaignBudgetOptions(ctx context.Context, in *SuggestSmartCampaignBudgetOptionsRequest, opts ...grpc.CallOption) (*SuggestSmartCampaignBudgetOptionsResponse, error)
}

type smartCampaignSuggestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartCampaignSuggestServiceClient(cc grpc.ClientConnInterface) SmartCampaignSuggestServiceClient {
	return &smartCampaignSuggestServiceClient{cc}
}

func (c *smartCampaignSuggestServiceClient) SuggestSmartCampaignBudgetOptions(ctx context.Context, in *SuggestSmartCampaignBudgetOptionsRequest, opts ...grpc.CallOption) (*SuggestSmartCampaignBudgetOptionsResponse, error) {
	out := new(SuggestSmartCampaignBudgetOptionsResponse)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v8.services.SmartCampaignSuggestService/SuggestSmartCampaignBudgetOptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartCampaignSuggestServiceServer is the server API for SmartCampaignSuggestService service.
// All implementations must embed UnimplementedSmartCampaignSuggestServiceServer
// for forward compatibility
type SmartCampaignSuggestServiceServer interface {
	// Returns BudgetOption suggestions.
	SuggestSmartCampaignBudgetOptions(context.Context, *SuggestSmartCampaignBudgetOptionsRequest) (*SuggestSmartCampaignBudgetOptionsResponse, error)
	mustEmbedUnimplementedSmartCampaignSuggestServiceServer()
}

// UnimplementedSmartCampaignSuggestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSmartCampaignSuggestServiceServer struct {
}

func (UnimplementedSmartCampaignSuggestServiceServer) SuggestSmartCampaignBudgetOptions(context.Context, *SuggestSmartCampaignBudgetOptionsRequest) (*SuggestSmartCampaignBudgetOptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestSmartCampaignBudgetOptions not implemented")
}
func (UnimplementedSmartCampaignSuggestServiceServer) mustEmbedUnimplementedSmartCampaignSuggestServiceServer() {
}

// UnsafeSmartCampaignSuggestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartCampaignSuggestServiceServer will
// result in compilation errors.
type UnsafeSmartCampaignSuggestServiceServer interface {
	mustEmbedUnimplementedSmartCampaignSuggestServiceServer()
}

func RegisterSmartCampaignSuggestServiceServer(s grpc.ServiceRegistrar, srv SmartCampaignSuggestServiceServer) {
	s.RegisterService(&SmartCampaignSuggestService_ServiceDesc, srv)
}

func _SmartCampaignSuggestService_SuggestSmartCampaignBudgetOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestSmartCampaignBudgetOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCampaignSuggestServiceServer).SuggestSmartCampaignBudgetOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v8.services.SmartCampaignSuggestService/SuggestSmartCampaignBudgetOptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCampaignSuggestServiceServer).SuggestSmartCampaignBudgetOptions(ctx, req.(*SuggestSmartCampaignBudgetOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartCampaignSuggestService_ServiceDesc is the grpc.ServiceDesc for SmartCampaignSuggestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartCampaignSuggestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.googleads.v8.services.SmartCampaignSuggestService",
	HandlerType: (*SmartCampaignSuggestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SuggestSmartCampaignBudgetOptions",
			Handler:    _SmartCampaignSuggestService_SuggestSmartCampaignBudgetOptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/ads/googleads/v8/services/smart_campaign_suggest_service.proto",
}
